/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: hiirusama (https://sketchfab.com/hiirusama)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ysl-high-heels-9f7c5266f7da43d6bbd5a881d49f57aa
Title: YSL High Heels
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

function Model(props) {
  const { nodes, materials } = useGLTF('/models/ysl_high_heels.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.HH_base_0.geometry}
            material={materials.base}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.HH_black_metal_0.geometry}
            material={materials.black_metal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.HH_sole_0.geometry}
            material={materials.sole}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.HH_Material001_0.geometry}
            material={materials['Material.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.HH_topPiece_0.geometry}
            material={materials.topPiece}
          />
        </group>
      </group>
    </group>
  )
}

export default Model

useGLTF.preload('/models/ysl_high_heels.glb')

